name: Continuous Delivery
on:
    push:
        branches: "develop"
 
env:
  IMAGE_NAME: simple-api-java
  AZURE_WEBAPP_NAME: simple-api-java
 
jobs:

    build:
        runs-on: ubuntu-latest
        steps:             
        -  
            name: Git Checkout 
            uses: actions/checkout@v4 
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
            name: Build 
            uses: docker/build-push-action@v6 
            with: 
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
            
        steps:
        - 
            name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_PROFILE }}
              images: 'ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'